package sql

import (
	"reflect"
	"testing"
)

func TestLexer(t *testing.T) {
	tests := []struct {
		name     string
		sql      string
		expected []Token
	}{
		{
			"select wildcard",
			"SELECT * FROM test",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"select columns",
			"SELECT col_1, col_2 FROM test",
			[]Token{
				{Select, "SELECT"},
				{Identifier, "col_1"},
				{Comma, ","},
				{Identifier, "col_2"},
				{From, "FROM"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"select with where int",
			"SELECT col_1, col_2 FROM test WHERE col_1 = 10",
			[]Token{
				{Select, "SELECT"},
				{Identifier, "col_1"},
				{Comma, ","},
				{Identifier, "col_2"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col_1"},
				{Equals, "="},
				{Int, "10"},
				{EOF, ""},
			},
		},
		{
			"select with where string",
			"SELECT col_1, col_2 FROM test WHERE col_2 = 'green'",
			[]Token{
				{Select, "SELECT"},
				{Identifier, "col_1"},
				{Comma, ","},
				{Identifier, "col_2"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col_2"},
				{Equals, "="},
				{String, "green"},
				{EOF, ""},
			},
		},
		{
			"select with where string and int",
			"SELECT col_1, col_2 FROM test WHERE col_1 = 'green' AND col_2 = 5",
			[]Token{
				{Select, "SELECT"},
				{Identifier, "col_1"},
				{Comma, ","},
				{Identifier, "col_2"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col_1"},
				{Equals, "="},
				{String, "green"},
				{And, "AND"},
				{Identifier, "col_2"},
				{Equals, "="},
				{Int, "5"},
				{EOF, ""},
			},
		},
		{
			"select with limit",
			"SELECT col_1, col_2 FROM test WHERE col_1 = 'green' AND col_2 = 5 LIMIT 10",
			[]Token{
				{Select, "SELECT"},
				{Identifier, "col_1"},
				{Comma, ","},
				{Identifier, "col_2"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col_1"},
				{Equals, "="},
				{String, "green"},
				{And, "AND"},
				{Identifier, "col_2"},
				{Equals, "="},
				{Int, "5"},
				{Limit, "LIMIT"},
				{Int, "10"},
				{EOF, ""},
			},
		},
		{
			"create table",
			"CREATE TABLE test (col_1 STRING, col_2 INT)",
			[]Token{
				{Create, "CREATE"},
				{TableIdentifier, "TABLE"},
				{Identifier, "test"},
				{ParenOpen, "("},
				{Identifier, "col_1"},
				{Identifier, "STRING"},
				{Comma, ","},
				{Identifier, "col_2"},
				{Identifier, "INT"},
				{ParenClose, ")"},
				{EOF, ""},
			},
		},
		{
			"create table with primary key",
			"CREATE TABLE test (col_1 STRING PRIMARY KEY, col_2 INT)",
			[]Token{
				{Create, "CREATE"},
				{TableIdentifier, "TABLE"},
				{Identifier, "test"},
				{ParenOpen, "("},
				{Identifier, "col_1"},
				{Identifier, "STRING"},
				{PrimaryKey, "PRIMARY KEY"},
				{Comma, ","},
				{Identifier, "col_2"},
				{Identifier, "INT"},
				{ParenClose, ")"},
				{EOF, ""},
			},
		},
		{
			"drop table",
			"DROP TABLE test",
			[]Token{
				{Drop, "DROP"},
				{TableIdentifier, "TABLE"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"insert table",
			"INSERT INTO test (col_1, col_2) VALUES ('value', 1)",
			[]Token{
				{Insert, "INSERT"},
				{Into, "INTO"},
				{Identifier, "test"},
				{ParenOpen, "("},
				{Identifier, "col_1"},
				{Comma, ","},
				{Identifier, "col_2"},
				{ParenClose, ")"},
				{Values, "VALUES"},
				{ParenOpen, "("},
				{String, "value"},
				{Comma, ","},
				{Int, "1"},
				{ParenClose, ")"},
				{EOF, ""},
			},
		},
		{
			"update table",
			"UPDATE test SET col_1 = 'value' WHERE col_2 = 5",
			[]Token{
				{Update, "UPDATE"},
				{Identifier, "test"},
				{Set, "SET"},
				{Identifier, "col_1"},
				{Equals, "="},
				{String, "value"},
				{Where, "WHERE"},
				{Identifier, "col_2"},
				{Equals, "="},
				{Int, "5"},
				{EOF, ""},
			},
		},
		{
			"delete table",
			"DELETE FROM test WHERE col_1 = 'value 123'",
			[]Token{
				{Delete, "DELETE"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col_1"},
				{Equals, "="},
				{String, "value 123"},
				{EOF, ""},
			},
		},
		{
			"create database",
			"CREATE DATABASE test",
			[]Token{
				{Create, "CREATE"},
				{DatabaseIdentifier, "DATABASE"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"drop database",
			"DROP DATABASE test",
			[]Token{
				{Drop, "DROP"},
				{DatabaseIdentifier, "DATABASE"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"show databases",
			"SHOW DATABASES",
			[]Token{
				{Show, "SHOW"},
				{DatabasesIdentifier, "DATABASES"},
				{EOF, ""},
			},
		},
		{
			"show tables",
			"SHOW TABLES",
			[]Token{
				{Show, "SHOW"},
				{TablesIdentifier, "TABLES"},
				{EOF, ""},
			},
		},
		// New tests for additional operators
		{
			"not equals operator",
			"SELECT * FROM test WHERE col != 5",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{NotEquals, "!="},
				{Int, "5"},
				{EOF, ""},
			},
		},
		{
			"not equals operator diamond",
			"SELECT * FROM test WHERE col <> 5",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{NotEquals, "<>"},
				{Int, "5"},
				{EOF, ""},
			},
		},
		{
			"less than operator",
			"SELECT * FROM test WHERE col < 10",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{LessThan, "<"},
				{Int, "10"},
				{EOF, ""},
			},
		},
		{
			"greater than operator",
			"SELECT * FROM test WHERE col > 10",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{GreaterThan, ">"},
				{Int, "10"},
				{EOF, ""},
			},
		},
		{
			"less than or equal operator",
			"SELECT * FROM test WHERE col <= 10",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{LessThanOrEqual, "<="},
				{Int, "10"},
				{EOF, ""},
			},
		},
		{
			"greater than or equal operator",
			"SELECT * FROM test WHERE col >= 10",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{GreaterThanOrEqual, ">="},
				{Int, "10"},
				{EOF, ""},
			},
		},
		{
			"or keyword",
			"SELECT * FROM test WHERE col = 1 OR col = 2",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{Equals, "="},
				{Int, "1"},
				{Or, "OR"},
				{Identifier, "col"},
				{Equals, "="},
				{Int, "2"},
				{EOF, ""},
			},
		},
		{
			"is null",
			"SELECT * FROM test WHERE col IS NULL",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{Is, "IS"},
				{Null, "NULL"},
				{EOF, ""},
			},
		},
		{
			"is not null",
			"SELECT * FROM test WHERE col IS NOT NULL",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "col"},
				{Is, "IS"},
				{Not, "NOT"},
				{Null, "NULL"},
				{EOF, ""},
			},
		},
		{
			"like operator",
			"SELECT * FROM test WHERE name LIKE '%john%'",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Identifier, "name"},
				{Like, "LIKE"},
				{String, "%john%"},
				{EOF, ""},
			},
		},
		{
			"order by",
			"SELECT * FROM test ORDER BY col ASC",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Order, "ORDER"},
				{By, "BY"},
				{Identifier, "col"},
				{Asc, "ASC"},
				{EOF, ""},
			},
		},
		{
			"order by desc",
			"SELECT * FROM test ORDER BY col DESC",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Order, "ORDER"},
				{By, "BY"},
				{Identifier, "col"},
				{Desc, "DESC"},
				{EOF, ""},
			},
		},
		{
			"limit offset",
			"SELECT * FROM test LIMIT 10 OFFSET 5",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Limit, "LIMIT"},
				{Int, "10"},
				{Offset, "OFFSET"},
				{Int, "5"},
				{EOF, ""},
			},
		},
		{
			"count star",
			"SELECT COUNT(*) FROM test",
			[]Token{
				{Select, "SELECT"},
				{Count, "COUNT"},
				{ParenOpen, "("},
				{Wildcard, "*"},
				{ParenClose, ")"},
				{From, "FROM"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"distinct",
			"SELECT DISTINCT col FROM test",
			[]Token{
				{Select, "SELECT"},
				{Distinct, "DISTINCT"},
				{Identifier, "col"},
				{From, "FROM"},
				{Identifier, "test"},
				{EOF, ""},
			},
		},
		{
			"case insensitive keywords",
			"select * from test where col = 5",
			[]Token{
				{Select, "select"},
				{Wildcard, "*"},
				{From, "from"},
				{Identifier, "test"},
				{Where, "where"},
				{Identifier, "col"},
				{Equals, "="},
				{Int, "5"},
				{EOF, ""},
			},
		},
		{
			"not keyword",
			"SELECT * FROM test WHERE NOT col = 5",
			[]Token{
				{Select, "SELECT"},
				{Wildcard, "*"},
				{From, "FROM"},
				{Identifier, "test"},
				{Where, "WHERE"},
				{Not, "NOT"},
				{Identifier, "col"},
				{Equals, "="},
				{Int, "5"},
				{EOF, ""},
			},
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			actual := tokenize(test.sql)

			if !reflect.DeepEqual(test.expected, actual) {
				t.Errorf("Test Failed: Expected %v however got %v", test.expected, actual)
			}
		})
	}
}
